/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ActiveModel": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ActiveProvider": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AgentBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "AgentRunner": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AwsRegion": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BuildMonitor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ClawCenter": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "CoderAgent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ConcurrencyMonitor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ConfigTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CriticAgent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DashboardPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DeadMansSwitch": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DiscordBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EventHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GitHubToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeartbeatHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KnowledgeBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MCPAwsS3Server": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MCPAwsServer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MCPFetchServer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MCPFilesystemServer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MCPGitServer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MCPGoogleSearchServer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MCPPuppeteerServer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MCPWarmupHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MemoryTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MiniMaxApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Notifier": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OpenAIApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenRouterApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PlannerAgent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "QaAgent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RealtimeBridge": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RealtimeBus": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "ReflectorAgent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SlackBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StagingBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "TelegramBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TraceTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebhookApiV2": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}