/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    ActiveModel: {
      type: 'sst.sst.Secret';
      value: string;
    };
    ActiveProvider: {
      type: 'sst.sst.Secret';
      value: string;
    };
    AgentBus: {
      arn: string;
      name: string;
      type: 'sst.aws.Bus';
    };
    AwsRegion: {
      type: 'sst.sst.Secret';
      value: string;
    };
    BuildMonitor: {
      name: string;
      type: 'sst.aws.Function';
    };
    ClawCenter: {
      type: 'sst.aws.Nextjs';
      url: string;
    };
    CoderAgent: {
      name: string;
      type: 'sst.aws.Function';
    };
    ConfigTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    DashboardPassword: {
      type: 'sst.sst.Secret';
      value: string;
    };
    DeadMansSwitch: {
      name: string;
      type: 'sst.aws.Function';
    };
    EventHandler: {
      name: string;
      type: 'sst.aws.Function';
    };
    GitHubToken: {
      type: 'sst.sst.Secret';
      value: string;
    };
    HeartbeatHandler: {
      name: string;
      type: 'sst.aws.Function';
    };
    KnowledgeBucket: {
      name: string;
      type: 'sst.aws.Bucket';
    };
    MemoryTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    Notifier: {
      name: string;
      type: 'sst.aws.Function';
    };
    OpenAIApiKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
    OpenRouterApiKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
    PlannerAgent: {
      name: string;
      type: 'sst.aws.Function';
    };
    QaAgent: {
      name: string;
      type: 'sst.aws.Function';
    };
    RealtimeBridge: {
      name: string;
      type: 'sst.aws.Function';
    };
    RealtimeBus: {
      authorizer: string;
      endpoint: string;
      type: 'sst.aws.Realtime';
    };
    ReflectorAgent: {
      name: string;
      type: 'sst.aws.Function';
    };
    StagingBucket: {
      name: string;
      type: 'sst.aws.Bucket';
    };
    TelegramBotToken: {
      type: 'sst.sst.Secret';
      value: string;
    };
    TraceTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    WebhookApi: {
      type: 'sst.aws.ApiGatewayV2';
      url: string;
    };
    WorkerAgent: {
      name: string;
      type: 'sst.aws.Function';
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
