import { ITool } from './tool';

/**
 * Represents a tool call generated by an LLM.
 */
export interface ToolCall {
  /** Unique identifier for the tool call. */
  id: string;
  /** The type of the call, currently only 'function' is supported. */
  type: 'function';
  /** The specific function being called and its arguments. */
  function: {
    /** The name of the tool to execute. */
    name: string;
    /** JSON-formatted string of arguments for the tool. */
    arguments: string;
  };
}

/**
 * Valid roles for messages in a conversation.
 */
export enum MessageRole {
  /** Input from the human user. */
  USER = 'user',
  /** Response from the AI agent. */
  ASSISTANT = 'assistant',
  /** System-level instructions or constraints. */
  SYSTEM = 'system',
  /** Output from a tool execution. */
  TOOL = 'tool',
  /** Developer-level metadata or instructions. */
  DEVELOPER = 'developer',
}

/**
 * A single message in a conversation thread.
 */
export interface Message {
  /** The role of the message sender. */
  role: MessageRole;
  /** The textual content of the message. */
  content?: string;
  /** Optional tool calls requested by the assistant. */
  tool_calls?: ToolCall[];
  /** The ID of the tool call this message is responding to (if role is TOOL). */
  tool_call_id?: string;
  /** The name of the tool or agent this message is responding from. */
  name?: string;
  /** Optional human-readable name of the agent that generated this message. */
  agentName?: string;
  /** Link to the isolated mechanical monologue for this message */
  traceId?: string;
}

/**
 * Profiles that define the computational intensity and 'thinking' depth of the LLM.
 */
export enum ReasoningProfile {
  /** Prioritizes speed and cost for simple tasks. */
  FAST = 'fast',
  /** Balanced profile for standard agent interactions. */
  STANDARD = 'standard',
  /** Enables intermediate reasoning steps for complex problems. */
  THINKING = 'thinking',
  /** Maximum reasoning depth for critical strategic tasks. */
  DEEP = 'deep',
}

/**
 * Supported LLM service providers.
 */
export enum LLMProvider {
  /** OpenAI (GPT models). */
  OPENAI = 'openai',
  /** AWS Bedrock (Claude, Llama models). */
  BEDROCK = 'bedrock',
  /** OpenRouter (Aggregator for multiple providers). */
  OPENROUTER = 'openrouter',
}

/**
 * Specific model identifiers for OpenAI.
 */
export enum OpenAIModel {
  GPT_5_4 = 'gpt-5.4',
  GPT_5_MINI = 'gpt-5-mini',
}

/**
 * Specific model identifiers for AWS Bedrock.
 */
export enum BedrockModel {
  CLAUDE_4_6 = 'global.anthropic.claude-sonnet-4-6',
}

/**
 * Specific model identifiers for OpenRouter.
 */
export enum OpenRouterModel {
  GLM_5 = 'zhipu/glm-5',
  MINIMAX_2_5 = 'minimax/minimax-2.5',
  GEMINI_3_FLASH = 'google/gemini-3-flash-preview',
}

/**
 * Describes the capabilities supported by a specific LLM model or provider.
 */
export interface ICapabilities {
  /** List of reasoning profiles supported by this configuration. */
  supportedReasoningProfiles: ReasoningProfile[];
}

/**
 * Interface for LLM provider implementations.
 */
export interface IProvider {
  /**
   * Performs a completion call to the LLM.
   *
   * @param messages - The full conversation history.
   * @param tools - Optional list of tools the LLM can call.
   * @param profile - The desired reasoning profile.
   * @param model - Optional override for the model ID.
   * @param provider - Optional override for the provider name.
   * @returns A promise resolving to the AI's message response.
   */
  call(
    messages: Message[],
    tools?: ITool[],
    profile?: ReasoningProfile,
    model?: string,
    provider?: string
  ): Promise<Message>;

  /**
   * Retrieves the capabilities of a specific model.
   *
   * @param model - The model ID to query.
   * @returns A promise resolving to the capabilities object.
   */
  getCapabilities(model?: string): Promise<ICapabilities>;
}
