import { ITool } from './tool';

/**
 * Represents a tool call generated by an LLM.
 */
export interface ToolCall {
  /** Unique identifier for the tool call. */
  id: string;
  /** The type of the call, currently only 'function' is supported. */
  type: 'function';
  /** The specific function being called and its arguments. */
  function: {
    /** The name of the tool to execute. */
    name: string;
    /** JSON-formatted string of arguments for the tool. */
    arguments: string;
  };
}

/**
 * Valid roles for messages in a conversation.
 */
export enum MessageRole {
  /** Input from the human user. */
  USER = 'user',
  /** Response from the AI agent. */
  ASSISTANT = 'assistant',
  /** System-level instructions or constraints. */
  SYSTEM = 'system',
  /** Output from a tool execution. */
  TOOL = 'tool',
  /** Developer-level metadata or instructions. */
  DEVELOPER = 'developer',
}

/**
 * A single message in a conversation thread.
 */
export interface Message {
  /** The role of the message sender. */
  role: MessageRole;
  /** The textual content of the message. */
  content?: string;
  /** Optional tool calls requested by the assistant. */
  tool_calls?: ToolCall[];
  /** The ID of the tool call this message is responding to (if role is TOOL). */
  tool_call_id?: string;
  /** The name of the tool or agent this message is responding from. */
  name?: string;
  /** Optional human-readable name of the agent that generated this message. */
  agentName?: string;
  /** Link to the isolated mechanical monologue for this message */
  traceId?: string;
  /**
   * Optional attachments (images, files) associated with the message.
   */
  attachments?: Array<{
    type: 'image' | 'file';
    url?: string;
    base64?: string;
    name?: string;
    mimeType?: string;
  }>;
  /**
   * Optional usage statistics (tokens) for the message (usually only for ASSISTANT).
   */
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

/**
 * Profiles that define the computational intensity and 'thinking' depth of the LLM.
 */
export enum ReasoningProfile {
  /** Prioritizes speed and cost for simple tasks. */
  FAST = 'fast',
  /** Balanced profile for standard agent interactions. */
  STANDARD = 'standard',
  /** Enables intermediate reasoning steps for complex problems. */
  THINKING = 'thinking',
  /** Maximum reasoning depth for critical strategic tasks. */
  DEEP = 'deep',
}

/**
 * Supported LLM service providers.
 */
export enum LLMProvider {
  /** OpenAI (GPT models). */
  OPENAI = 'openai',
  /** AWS Bedrock (Claude, Llama models). */
  BEDROCK = 'bedrock',
  /** OpenRouter (Aggregator for multiple providers). */
  OPENROUTER = 'openrouter',
}

/**
 * Specific model identifiers for OpenAI.
 */
export enum OpenAIModel {
  /** High-tier reasoning model (GPT-5.4 family) */
  GPT_5_4 = 'gpt-5.4',
  /** Balanced standard reasoning model (GPT-5.4 family) */
  GPT_5_4_MINI = 'gpt-5.4-mini',
  /** Fast, cost-efficient reasoning model (GPT-5.4 family) */
  GPT_5_4_NANO = 'gpt-5.4-nano',
}

/**
 * Specific model identifiers for AWS Bedrock.
 */
export enum BedrockModel {
  CLAUDE_4_6 = 'global.anthropic.claude-sonnet-4-6',
}

/**
 * Specific model identifiers for OpenRouter.
 */
export enum OpenRouterModel {
  GLM_5 = 'zhipu/glm-5',
  MINIMAX_M2_7 = 'minimax/minimax-m2.7',
  GEMINI_3_FLASH = 'google/gemini-3-flash-preview',
}

/**
 * Describes the capabilities supported by a specific LLM model or provider.
 */
export interface ICapabilities {
  /** List of reasoning profiles supported by this configuration. */
  supportedReasoningProfiles: ReasoningProfile[];
  /** Optional cap for reasoning effort (e.g. 'high' for mini models). */
  maxReasoningEffort?: string;
  /** Whether the model supports structured JSON output (json_schema). */
  supportsStructuredOutput?: boolean;
  /** The maximum context window size (tokens) for this model. */
  contextWindow?: number;
}

/**
 * Format specification for the LLM response, used to enforce structured output.
 */
export interface ResponseFormat {
  /** The type of format, currently only 'json_schema' is supported for strict enforcement. */
  type: 'json_schema';
  /** The detailed JSON schema definition. */
  json_schema: {
    /** A descriptive name for the schema. */
    name: string;
    /** Optional description of what the response format is for. */
    description?: string;
    /** Whether to strictly enforce the schema (OpenAI specific). */
    strict: boolean;
    /** The actual JSON schema object. */
    schema: Record<string, unknown>;
  };
}

/**
 * Interface for LLM provider implementations.
 */
export interface IProvider {
  /**
   * Performs a completion call to the LLM.
   *
   * @param messages - The full conversation history.
   * @param tools - Optional list of tools the LLM can call.
   * @param profile - The desired reasoning profile.
   * @param model - Optional override for the model ID.
   * @param provider - Optional override for the provider name.
   * @param responseFormat - Optional structured format for the response.
   * @returns A promise resolving to the AI's message response.
   */
  call(
    messages: Message[],
    tools?: ITool[],
    profile?: ReasoningProfile,
    model?: string,
    provider?: string,
    responseFormat?: ResponseFormat
  ): Promise<Message>;

  /**
   * Retrieves the capabilities of a specific model.
   *
   * @param model - The model ID to query.
   * @returns A promise resolving to the capabilities object.
   */
  getCapabilities(model?: string): Promise<ICapabilities>;
}
