import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  PutCommand,
  UpdateCommand,
  QueryCommand,
} from '@aws-sdk/lib-dynamodb';
import { Resource } from 'sst';
import { SSTResource } from './types/index';
import { v4 as uuidv4 } from 'uuid';
import { TRACE_TYPES, TRACE_STATUS } from './constants';
import { logger } from './logger';

const client = new DynamoDBClient({});
const docClient = DynamoDBDocumentClient.from(client, {
  marshallOptions: {
    removeUndefinedValues: true,
  },
});
const typedResource = Resource as unknown as SSTResource;

const TRACE_CONFIG = {
  TTL_DAYS: 7,
  SECONDS_IN_DAY: 86400,
} as const;

/**
 * Represents a single step within a trace (e.g., an LLM call or a tool execution).
 */
export interface TraceStep {
  /** Unique identifier for the step. */
  stepId: string;
  /** The type of event being recorded. */
  type: (typeof TRACE_TYPES)[keyof typeof TRACE_TYPES];
  /** The content of the step (e.g., LLM prompts, tool results). */
  content: unknown;
  /** Timestamp (Unix epoch) of the step. */
  timestamp: number;
  /** Optional metadata associated with the step. */
  metadata?: Record<string, unknown>;
}

/**
 * Full record of an agent's reasoning trace.
 */
export interface Trace {
  /** Unique identifier for the trace. */
  traceId: string;
  /** The ID of the user or session the trace belongs to. */
  userId: string;
  /** The origin of the request (e.g., 'dashboard', 'telegram', 'system'). */
  source: string;
  /** Start timestamp of the trace. */
  timestamp: number;
  /** Current status of the trace. */
  status: (typeof TRACE_STATUS)[keyof typeof TRACE_STATUS] | string;
  /** Initial context provided when the trace was started. */
  initialContext: Record<string, unknown>;
  /** Sequential list of steps performed during the trace. */
  steps: TraceStep[];
  /** Expiration timestamp for DynamoDB TTL. */
  expiresAt: number;
  /** Final textual response generated by the agent. */
  finalResponse?: string;
  /** End timestamp of the trace. */
  endTime?: number;
  /** Additional metadata for the trace. */
  metadata?: Record<string, unknown>;
}

/**
 * ClawTracer provides observability into an agent's internal reasoning process
 * by persisting steps and metadata to DynamoDB.
 */
export class ClawTracer {
  private tableName: string = typedResource.TraceTable.name;
  private traceId: string;
  private userId: string;
  private source: string;
  private startTime: number;

  /**
   * Initializes a new ClawTracer instance.
   *
   * @param userId - Unique identifier for the user or session.
   * @param source - Origin of the request.
   * @param traceId - Optional override for the trace ID.
   */
  constructor(userId: string, source: string = 'unknown', traceId?: string) {
    this.userId = userId;
    this.source = source;
    this.traceId = traceId || uuidv4();
    this.startTime = Date.now();
  }

  /**
   * Initializes a new trace in DynamoDB.
   *
   * @param initialContext - Initial context for the trace (e.g., user input).
   * @returns A promise that resolves to the trace ID.
   */
  async startTrace(initialContext: Record<string, unknown>): Promise<string> {
    const expiresAt =
      Math.floor(Date.now() / 1000) + TRACE_CONFIG.TTL_DAYS * TRACE_CONFIG.SECONDS_IN_DAY;

    try {
      await docClient.send(
        new PutCommand({
          TableName: this.tableName,
          Item: {
            traceId: this.traceId,
            userId: this.userId,
            source: this.source,
            timestamp: this.startTime,
            status: TRACE_STATUS.STARTED,
            initialContext,
            steps: [],
            expiresAt,
          },
          ConditionExpression: 'attribute_not_exists(traceId)',
        })
      );
    } catch (e: any) {
      if (e.name === 'ConditionalCheckFailedException') {
        logger.info(`Trace ${this.traceId} already exists, skipping initialization.`);
      } else {
        throw e;
      }
    }
    return this.traceId;
  }

  /**
   * Adds a step to the current trace.
   *
   * @param step - The step content and type.
   * @returns A promise that resolves when the step is added.
   */
  async addStep(step: Omit<TraceStep, 'stepId' | 'timestamp'>): Promise<void> {
    const fullStep: TraceStep = {
      ...step,
      stepId: uuidv4(),
      timestamp: Date.now(),
    } as TraceStep;

    await docClient.send(
      new UpdateCommand({
        TableName: this.tableName,
        Key: { traceId: this.traceId },
        UpdateExpression: 'SET #steps = list_append(if_not_exists(#steps, :empty_list), :step)',
        ExpressionAttributeNames: { '#steps': 'steps' },
        ExpressionAttributeValues: {
          ':step': [fullStep],
          ':empty_list': [],
        },
      })
    );
  }

  /**
   * Ends the trace with a final response and optional metadata.
   *
   * @param finalResponse - The final response sent to the user.
   * @param metadata - Additional metadata for the trace.
   * @returns A promise that resolves when the trace is closed.
   */
  async endTrace(finalResponse: string, metadata?: Record<string, unknown>): Promise<void> {
    await docClient.send(
      new UpdateCommand({
        TableName: this.tableName,
        Key: { traceId: this.traceId },
        UpdateExpression:
          'SET #status = :status, finalResponse = :resp, endTime = :end, metadata = :meta',
        ExpressionAttributeNames: { '#status': 'status' },
        ExpressionAttributeValues: {
          ':status': TRACE_STATUS.COMPLETED,
          ':resp': finalResponse,
          ':end': Date.now(),
          ':meta': metadata || {},
        },
      })
    );
  }

  /**
   * Returns the current trace ID.
   *
   * @returns The trace ID string.
   */
  getTraceId(): string {
    return this.traceId;
  }

  /**
   * Retrieves a full trace from DynamoDB by its ID.
   *
   * @param traceId - The trace ID to retrieve.
   * @returns A promise resolving to the full trace object or undefined if not found.
   */
  static async getTrace(traceId: string): Promise<Trace | undefined> {
    const response = await docClient.send(
      new QueryCommand({
        TableName: typedResource.TraceTable.name,
        KeyConditionExpression: 'traceId = :tid',
        ExpressionAttributeValues: { ':tid': traceId },
        Limit: 1,
      })
    );
    return response.Items?.[0] as Trace | undefined;
  }
}
