name: Auto Cleanup Caches

on:
  schedule:
    # Run every Sunday at 3:00 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    name: Cache Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Prune pnpm store
        run: pnpm store prune

      - name: Clear obsolete workflow caches
        uses: actions/github-script@v9
        with:
          script: |
            const { owner, repo } = context.repo;
            const caches = await github.rest.actions.getActionsCacheList({
              owner,
              repo,
            });
            for (const cache of caches.data.actions_caches) {
              // Delete caches older than a week
              const createdAt = new Date(cache.created_at);
              const oneWeekAgo = new Date();
              oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
              if (createdAt < oneWeekAgo) {
                console.log(`Deleting cache ${cache.key}...`);
                await github.rest.actions.deleteActionsCacheById({
                  owner,
                  repo,
                  cache_id: cache.id,
                });
              }
            }
